FROM node:alpine

WORKDIR /usr/src/nuxt-app

COPY ./package.json ./
COPY ./yarn-lock.json ./

RUN yarn install
RUN yarn build

COPY ./ .

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000 

ENTRYPOINT ["node", ".output/server/index.mjs"]