FROM node:20-alpine

RUN apk --no-cache add curl

WORKDIR /usr/src/nuxt-app

COPY ./package.json ./

RUN npm install

COPY ./ .

RUN npm run build

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000

HEALTHCHECK CMD curl -f http://localhost:8080/api/health-check || exit 1

ENTRYPOINT ["node", ".output/server/index.mjs"]
